### ISSUE TITLE
HaveCodeError can panic

### ISSUE THREAD

**Issue by didil** [pioz/tvdb#3]
I think this [type assertion](https://github.com/pioz/tvdb/blob/0359b91e22a811bd02e0d32f9998c97934eb00eb/request_error.go#L22) should use a safe type assertion 

```
serr,ok := err.(*RequestError)
```
as it currently stands if I do a downstream error check using HaveCodeError and it's not a RequestError it panics.
I could do the .(*RequestError) check downstream but the general Go guideline is that library code shouldn't panic ...
Other than that thanks for this helpful library !

**Comment by pioz** [comment]
Thanks for reporting this issue. You are right! I've fixed the problem with this commit. Can you check on master if the problem is really fixed?

**Comment by didil** [comment]
great thanks !
